######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 26 12:32:06 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++11
# CONFIG += debug
QT += opengl

# Input
HEADERS += landscape.h treedialog.h
FORMS += treedialog.ui
SOURCES += landscape.cpp treedialog.cpp main.cpp
